services:
  - type: web
    name: ai-music-studio
    env: python
    pythonVersion: 3.11
    buildCommand: "chmod +x ./render-build.sh && ./render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: AUDD_API_TOKEN
        sync: false
      - key: XFORMERS_DISABLED
        value: "1"
      - key: NO_XFORMERS
        value: "1"
